# Generated by Django 2.2.24 on 2021-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default=0, max_length=15, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
    ]
